### ISSUE TITLE
extract-text-webpack-plugin使用报错

### ISSUE THREAD

**Issue by lixin5257xx** [icarusion/vue-book#56]
P193页，按照对应的代码，进行安装，运行，会报错。报错信息如下，求解答：
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Ent
rypoint instead
    at Chunk.get (D:\lixin\VUE系列\vue-单页面\webpack\node_modules\webpack\lib\C
hunk.js:741:9)
    at D:\lixin\VUE系列\vue-单页面\webpack\node_modules\extract-text-webpack-plu
gin\index.js:260:40
    at Array.forEach (<anonymous>)
    at ExtractTextPlugin.<anonymous> (D:\lixin\VUE系列\vue-单页面\webpack\node_m
odules\extract-text-webpack-plugin\index.js:255:11)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\lixin\VUE系列\vue
-单页面\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:
7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\lixin\VUE系列\vue-单
页面\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (D:\lixin\VUE系列\vue-单页面\webpack\node_modules\webpac
k\lib\Compilation.js:904:27)
    at hooks.make.callAsync.err (D:\lixin\VUE系列\vue-单页面\webpack\node_module
s\webpack\lib\Compiler.js:494:17)
    at _err0 (eval at create (D:\lixin\VUE系列\vue-单页面\webpack\node_modules\t
apable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (D:\lixin\VUE系列\vue-单页面\webpack\node_modules\webpack
\lib\Compilation.js:770:12)
    at processModuleDependencies.err (D:\lixin\VUE系列\vue-单页面\webpack\node_m
odules\webpack\lib\Compilation.js:709:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo@1.0.0 dev: `webpack-dev-server --open --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-06-05T0
6_09_32_783Z-debug.log

**Comment by lixin5257xx** [comment]
通过N天奋斗已解决~ 解决办法：
npm install extract-text-webpack-plugin@next
希望看到的同学，少走一些弯路。。。。阿门
